implement stores growth, random initial date for store, refine docker compose

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -2,7 +2,7 @@ x-convenience-store-simulator:
   &common
   image: simulator/convenience-store:0.1
   build:
-    dockerfile: dockerfile
+    dockerfile: Dockerfile
   environment:
     &common-env
     POSTGRES_DB_HOST: postgres
@@ -12,14 +12,13 @@ x-convenience-store-simulator:
     POSTGRES_DB_PASSWORD: store
   env_file:
     - simulator.env
-  networks:
-    - backend
   volumes:
     - simulator-data:/app/data
   depends_on:
     &common-depends-on
     postgres:
       condition: service_healthy
+
 services:
   postgres:
     image: postgres:alpine3.19
@@ -29,33 +28,47 @@ services:
       POSTGRES_DB: store
     volumes:
       - postgres-db:/var/lib/postgresql/data
-    networks:
-      - backend
     healthcheck:
-      test: [ "CMD-SHELL", "pg_isready", "-d", "store", "-U", "store" ]
+      test: [ "CMD-SHELL", "pg_isready", "-d", "$${POSTGRES_DB}", "-U", "$${POSTGRES_USER}" ]
       interval: 10s
       retries: 5
       start_period: 5s
     restart: always
+
   simulator:
     <<: *common
-    command: run
+    command:
+      - run
+    environment:
+      <<: *common-env
     restart: always
     depends_on:
       <<: *common-depends-on
       init:
         condition: service_completed_successfully
+
   init:
     <<: *common
     entrypoint: /bin/sh
     command:
       - -c
       - |
+        export SIMULATOR_INITIAL_DATE="$${_INITIAL_DATE}"
+        export SIMULATOR_MAX_DATE="$${_INITIAL_MAX_DATE}"
+        export SIMULATOR_INTERVAL="$${_INITIAL_SIMULATOR_INTERVAL:-1}"
+        export SIMULATOR_SPEED="$${_INITIAL_SIMULATOR_SPEED:-1200}"
+        export SIMULATOR_INITIAL_STORES="$${_INITIAL_STORES:-100}"
+        export SIMULATOR_INITIAL_STORES_RANGE_DAYS="$${_INITIAL_STORES_RANGE_DAYS:-180}"
+        export SIMULATOR_STORE_GROWTH_RATE="$${_INITIAL_STORE_GROWTH_RATE:-0.5}"
+        export SIMULATOR_STORE_MARKET_POPULATION="$${_INITIAL_STORE_MARKET_POPULATION:-15_000}"
+        export SIMULATOR_STORE_INITIAL_EMPLOYEES="$${_INITIAL_STORE_EMPLOYEES:-4}"
+
         if [ -e "/app/data/checkpoint.pkl" ]; then
           echo "Simulator has exists."
           exit 0
         fi
 
+        SEED=${_SEED:-}
         echo "Initializing simulator..."
         if [ -z "$${SEED}" ]; then
           python -m simulator init
@@ -66,17 +79,29 @@ services:
         if [ $? -eq 0 ]; then
           echo "Succefully initialize simulator."
         else
-          echo "An error was occured during the initialization."
+          echo "An error was occured during while initializing the simulator.."
           exit 1
         fi
-    environment:
-      <<: *common-env
-      SEED: ${SEED}
 
-networks:
-  backend:
-    name: convenience-store-simulator-network
-    driver: bridge
+        if [ -z "$${_INITIAL_DATE}" ]; then
+          echo "'_INITIAL_DATE' is not set. Initial simulation will be not performed."
+          echo "The next run will have simulation to run start from '$(date +%Y-%m-%d)'."
+
+        else
+          if [ -z "$${_INITIAL_MAX_DATE}" ]; then
+            export SIMULATOR_MAX_DATE="$(date +'%Y-%m-%d')"
+            echo "'_INITIAL_MAX_DATE' is not set. It will be set as today."
+          fi
+          echo "Running initial simulation from '$${SIMULATOR_INITIAL_DATE}' until '$${SIMULATOR_MAX_DATE}' with simulation speed 1:$${SIMULATOR_SPEED}."
+          python -m simulator run --max-datetime=$${SIMULATOR_MAX_DATE} --skip-step --checkpoint=$${_INITIAL_SIMULATOR_CHECKPOINT_INTERVAL:-0}
+        fi
+
+        if [ $? -eq 0 ]; then
+          echo "Initial simulation has been completed. The next run will have simulation to run start from '$${SIMULATOR_MAX_DATE}'."
+        else
+          echo "An error was occured while running the simulation."
+          exit 1
+        fi
 
 volumes:
   postgres-db:
